spring.datasource.url=jdbc:postgresql://localhost:5432/northwind
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Inicialização do Schema (Se você estiver usando Spring Session)
spring.session.jdbc.initialize-schema=always

# Context Path (Opcional, deixe comentado se não for usar)
# server.servlet.context-path=/microservice